<?php 
require('header.php');
?>

		<div class="wdu-pops-navbar wdu-box-shadow wdu-min-width wdu-hidden wdu-conceal wdu-anim">
			<div class="wdu-pops-channel wdu-back-whits wdu-part-rows wdu-line-top wdu-hidden">
				选择频道
			</div>
			<a class="wdu-pops-btns wdu-back-whits wdu-text-black wdu-text-center wdu-event wdu-hide-sm wdu-icon-font wdu-icon-fenlei" href="javascript:;"></a>
			<ul class="wdu-pops-list wdu-font-size wdu-back-whits wdu-part-rows">
				<li class="wdu-col-sm2"><a class="wdu-part-eone" href="/">首页</a></li>
				<li class="wdu-col-sm2"><a class="wdu-part-eone" href="/index.php/vod/detail/id/11148.html">如懿传</a></li>
				<li class="wdu-col-sm2"><a class="wdu-part-eone" href="/index.php/vod/type/id/1.html">电影</a></li>
				<li class="wdu-col-sm2 wdu-this"><a class="wdu-part-eone" href="/index.php/vod/type/id/2.html">连续剧</a></li>
				<li class="wdu-col-sm2"><a class="wdu-part-eone" href="/index.php/vod/type/id/27.html">直播</a></li>
				<li class="wdu-col-sm2"><a class="wdu-part-eone" href="/index.php/vod/type/id/3.html">综艺</a></li>
				<li class="wdu-col-sm2"><a class="wdu-part-eone" href="/index.php/vod/type/id/4.html">动漫</a></li>
				<li class="wdu-col-sm2"><a class="wdu-part-eone" href="/index.php/vod/type/id/28.html">小视频</a></li>
				<li class="wdu-col-sm2"><a class="wdu-part-eone" href="/index.php/art/index.html">博客</a></li>
				<li class="wdu-col-sm2"><a class="wdu-part-eone" href="/index.php/art/type/id/5.html">站内</a></li>
				<li class="wdu-col-sm2"><a class="wdu-part-eone" href="/index.php/art/type/id/29.html">新闻</a></li>
				<li class="wdu-col-sm2"><a class="wdu-part-eone" href="/index.php/topic/index.html">专题</a></li>
			</ul>
		</div>
		<div class="wdu-pops-search wdu-hidden wdu-conceal wdu-anim wdu-anim-upbit">
			<div class="wdu-pops-case wdu-back-ashen wdu-box-shadow">
				<div class="wdu-pops-key">
				</div>
				<div class="wdu-pops-box">
					<div class="wdu-pops-hot">
						<div class="wdu-pops-title wdu-back-whits wdu-part-rows wdu-line-bottom">
							热门搜索
						</div>
						<ul class="wdu-pops-list wdu-back-whits wdu-part-rows">
							<li class="wdu-col-xs6"><a class="wdu-event wdu-part-eone" href="/index.php/vod/search/wd/%E5%8F%98%E5%BD%A2%E9%87%91%E5%88%9A.html"><span class="wdu-part-nums wdu-part-num1">1</span><span class="wdu-name">变形金刚</span></a></li>
							<li class="wdu-col-xs6"><a class="wdu-event wdu-part-eone" href="/index.php/vod/search/wd/%E7%81%AB%E5%BD%B1%E5%BF%8D%E8%80%85.html"><span class="wdu-part-nums wdu-part-num2">2</span><span class="wdu-name">火影忍者</span></a></li>
							<li class="wdu-col-xs6"><a class="wdu-event wdu-part-eone" href="/index.php/vod/search/wd/%E5%A4%8D%E4%BB%87%E8%80%85%E8%81%94%E7%9B%9F.html"><span class="wdu-part-nums wdu-part-num3">3</span><span class="wdu-name">复仇者联盟</span></a></li>
							<li class="wdu-col-xs6"><a class="wdu-event wdu-part-eone" href="/index.php/vod/search/wd/%E6%88%98%E7%8B%BC.html"><span class="wdu-part-nums wdu-part-num4">4</span><span class="wdu-name">战狼</span></a></li>
							<li class="wdu-col-xs6"><a class="wdu-event wdu-part-eone" href="/index.php/vod/search/wd/%E7%BA%A2%E6%B5%B7%E8%A1%8C%E5%8A%A8.html"><span class="wdu-part-nums wdu-part-num5">5</span><span class="wdu-name">红海行动</span></a></li>
							<li class="wdu-col-xs6"><a class="wdu-event wdu-part-eone" href="/index.php/vod/search/wd/%E4%B8%9C%E4%BA%AC%E9%A3%9F%E5%B0%B8%E9%AC%BC.html"><span class="wdu-part-nums wdu-part-num6">6</span><span class="wdu-name">东京食尸鬼</span></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div class="wdu-pops-record wdu-box-shadow wdu-hidden wdu-conceal wdu-anim wdu-anim-upbit">
		</div>
		<div class="wdu-pops-code wdu-back-whits wdu-box-shadow wdu-hidden wdu-conceal wdu-anim wdu-anim-upbit">
			<div class="wdu-pops-cont">
				<p style="text-align: center;">
					<img src="http://img.fed.cm/public.jpg" alt="公众号"/>
				</p>
				<p style="text-align: center;">
					欢迎关注微信公众号
				</p>
			</div>
		</div>
		<div class="wdu-pops-user wdu-box-shadow wdu-back-whits wdu-hidden wdu-conceal wdu-anim wdu-anim-upbit">
			<ul class="wdu-pops-list wdu-font-size wdu-back-whits">
				<li><a href="/index.php/user/index.html">游客</a></li>
				<li><a href="/index.php/user/info.html">修改资料</a></li>
				<li><a href="/index.php/user/favs.html">我的收藏</a></li>
				<li><a href="/index.php/user/plays.html">播放记录</a></li>
				<li><a href="/index.php/user/downs.html">下载记录</a></li>
				<li><a href="/index.php/user/buy.html">充值中心</a></li>
				<li><a href="/index.php/user/upgrade.html">升级会员</a></li>
				<li><a href="/index.php/user/logout.html">退出登录</a></li>
			</ul>
		</div>
	</div>
</div>
<div class="wdu-tabr-info wdu-back-whits wdu-min-width wdu-line-top wdu-hide-sm">
	<ul class="wdu-part-rows">
		<li class="wdu-text-center"><a class="wdu-visible" href="/"><i class="wdu-icon-font wdu-icon-shouye"></i><span class="wdu-font-xii">首页</span></a></li>
		<li class="wdu-text-center"><a class="wdu-visible" href="/index.php/art/index.html"><i class="wdu-icon-font wdu-icon-zixun"></i><span class="wdu-font-xii">博客</span></a></li>
		<li class="wdu-text-center"><a class="wdu-visible" href="/index.php/gbook/index.html"><i class="wdu-icon-font wdu-icon-liuyan"></i><span class="wdu-font-xii">求片</span></a></li>
		<li class="wdu-text-center"><a class="wdu-visible" href="/index.php/topic/index.html"><i class="wdu-icon-font wdu-icon-zhuanti"></i><span class="wdu-font-xii">专题</span></a></li>
		<li class="wdu-text-center"><a class="wdu-visible" href="/index.php/user/login.html"><i class="wdu-icon-font wdu-icon-yonghu"></i><span class="wdu-font-xii">我的</span></a></li>
	</ul>
</div>
<div class="wdu-main-info wdu-min-width">
	<div class="wdu-part-case">
		<div class="wdu-casc-info wdu-part-layout wdu-back-whits wdu-part-rows">
			<div class="wdu-casc-list wdu-part-rows">
				<dl>
					<dt>频道</dt>
					<dd><a class="wdu-text-center" href="/index.php/vod/show/id/1.html">电影</a></dd><dd><a class="wdu-text-center wdu-this wdu-text-green" href="/index.php/vod/show/id/2.html">连续剧</a></dd><dd><a class="wdu-text-center" href="/index.php/vod/show/id/27.html">直播</a></dd><dd><a class="wdu-text-center" href="/index.php/vod/show/id/3.html">综艺</a></dd><dd><a class="wdu-text-center" href="/index.php/vod/show/id/4.html">动漫</a></dd><dd><a class="wdu-text-center" href="/index.php/vod/show/id/28.html">小视频</a></dd>
				</dl>
				<dl>
					<dt>分类</dt>
					<dd><a class="wdu-text-center wdu-this wdu-text-green" href="/index.php/vod/show.html">全部</a></dd><dd><a class="wdu-text-center" href="/index.php/vod/show/id/13.html">国产剧</a></dd><dd><a class="wdu-text-center" href="/index.php/vod/show/id/15.html">日本剧</a></dd><dd><a class="wdu-text-center" href="/index.php/vod/show/id/14.html">韩国剧</a></dd><dd><a class="wdu-text-center" href="/index.php/vod/show/id/16.html">欧美剧</a></dd><dd><a class="wdu-text-center" href="/index.php/vod/show/id/21.html">泰国剧</a></dd><dd><a class="wdu-text-center" href="/index.php/vod/show/id/22.html">香港剧</a></dd><dd><a class="wdu-text-center" href="/index.php/vod/show/id/23.html">台湾剧</a></dd><dd><a class="wdu-text-center" href="/index.php/vod/show/id/24.html">其他剧</a></dd>
				</dl>
				<dl>
					<dt>地区</dt>
					<dd><a class="wdu-this wdu-text-green" href="/index.php/vod/show/id/2.html">全部</a></dd><dd><a href="/index.php/vod/show/area/%E5%86%85%E5%9C%B0/id/2.html">内地</a></dd><dd><a href="/index.php/vod/show/area/%E9%9F%A9%E5%9B%BD/id/2.html">韩国</a></dd><dd><a href="/index.php/vod/show/area/%E9%A6%99%E6%B8%AF/id/2.html">香港</a></dd><dd><a href="/index.php/vod/show/area/%E5%8F%B0%E6%B9%BE/id/2.html">台湾</a></dd><dd><a href="/index.php/vod/show/area/%E6%97%A5%E6%9C%AC/id/2.html">日本</a></dd><dd><a href="/index.php/vod/show/area/%E7%BE%8E%E5%9B%BD/id/2.html">美国</a></dd><dd><a href="/index.php/vod/show/area/%E6%B3%B0%E5%9B%BD/id/2.html">泰国</a></dd><dd><a href="/index.php/vod/show/area/%E8%8B%B1%E5%9B%BD/id/2.html">英国</a></dd><dd><a href="/index.php/vod/show/area/%E6%96%B0%E5%8A%A0%E5%9D%A1/id/2.html">新加坡</a></dd><dd><a href="/index.php/vod/show/area/%E5%85%B6%E4%BB%96/id/2.html">其他</a></dd>
				</dl>
				<dl>
					<dt>年代</dt>
					<dd><a class="wdu-this wdu-text-green" href="/index.php/vod/show/id/2.html">全部</a></dd><dd><a href="/index.php/vod/show/id/2/year/2018.html">2018</a></dd><dd><a href="/index.php/vod/show/id/2/year/2017.html">2017</a></dd><dd><a href="/index.php/vod/show/id/2/year/2016.html">2016</a></dd><dd><a href="/index.php/vod/show/id/2/year/2015.html">2015</a></dd><dd><a href="/index.php/vod/show/id/2/year/2014.html">2014</a></dd><dd><a href="/index.php/vod/show/id/2/year/2013.html">2013</a></dd><dd><a href="/index.php/vod/show/id/2/year/2012.html">2012</a></dd><dd><a href="/index.php/vod/show/id/2/year/2011.html">2011</a></dd><dd><a href="/index.php/vod/show/id/2/year/2010.html">2010</a></dd><dd><a href="/index.php/vod/show/id/2/year/2009.html">2009</a></dd><dd><a href="/index.php/vod/show/id/2/year/2008.html">2008</a></dd><dd><a href="/index.php/vod/show/id/2/year/2006.html">2006</a></dd><dd><a href="/index.php/vod/show/id/2/year/2005.html">2005</a></dd><dd><a href="/index.php/vod/show/id/2/year/2004.html">2004</a></dd>
				</dl>
				<dl>
					<dt>主演</dt>
					<dd><a class="wdu-this wdu-text-green" href="/index.php/vod/show/id/2.html">全部</a></dd><dd><a href="/index.php/vod/show/actor/%E7%8E%8B%E5%AE%9D%E5%BC%BA/id/2.html">王宝强</a></dd><dd><a href="/index.php/vod/show/actor/%E8%83%A1%E6%AD%8C/id/2.html">胡歌</a></dd><dd><a href="/index.php/vod/show/actor/%E9%9C%8D%E5%BB%BA%E5%8D%8E/id/2.html">霍建华</a></dd><dd><a href="/index.php/vod/show/actor/%E8%B5%B5%E4%B8%BD%E9%A2%96/id/2.html">赵丽颖</a></dd><dd><a href="/index.php/vod/show/actor/%E5%88%98%E6%B6%9B/id/2.html">刘涛</a></dd><dd><a href="/index.php/vod/show/actor/%E5%88%98%E8%AF%97%E8%AF%97/id/2.html">刘诗诗</a></dd><dd><a href="/index.php/vod/show/actor/%E9%99%88%E4%BC%9F%E9%9C%86/id/2.html">陈伟霆</a></dd><dd><a href="/index.php/vod/show/actor/%E5%90%B4%E5%A5%87%E9%9A%86/id/2.html">吴奇隆</a></dd><dd><a href="/index.php/vod/show/actor/%E9%99%86%E6%AF%85/id/2.html">陆毅</a></dd><dd><a href="/index.php/vod/show/actor/%E5%94%90%E5%AB%A3/id/2.html">唐嫣</a></dd><dd><a href="/index.php/vod/show/actor/%E5%85%B3%E6%99%93%E5%BD%A4/id/2.html">关晓彤</a></dd><dd><a href="/index.php/vod/show/actor/%E5%AD%99%E4%BF%AA/id/2.html">孙俪</a></dd><dd><a href="/index.php/vod/show/actor/%E6%9D%8E%E6%98%93%E5%B3%B0/id/2.html">李易峰</a></dd><dd><a href="/index.php/vod/show/actor/%E5%BC%A0%E7%BF%B0/id/2.html">张翰</a></dd><dd><a href="/index.php/vod/show/actor/%E6%9D%8E%E6%99%A8/id/2.html">李晨</a></dd><dd><a href="/index.php/vod/show/actor/%E8%8C%83%E5%86%B0%E5%86%B0/id/2.html">范冰冰</a></dd><dd><a href="/index.php/vod/show/actor/%E6%9E%97%E5%BF%83%E5%A6%82/id/2.html">林心如</a></dd><dd><a href="/index.php/vod/show/actor/%E6%96%87%E7%AB%A0/id/2.html">文章</a></dd><dd><a href="/index.php/vod/show/actor/%E9%A9%AC%E4%BC%8A%E7%90%8D/id/2.html">马伊琍</a></dd><dd><a href="/index.php/vod/show/actor/%E4%BD%9F%E5%A4%A7%E4%B8%BA/id/2.html">佟大为</a></dd><dd><a href="/index.php/vod/show/actor/%E5%AD%99%E7%BA%A2%E9%9B%B7/id/2.html">孙红雷</a></dd><dd><a href="/index.php/vod/show/actor/%E9%99%88%E5%BB%BA%E6%96%8C/id/2.html">陈建斌</a></dd><dd><a href="/index.php/vod/show/actor/%E6%9D%8E%E5%B0%8F%E7%92%90/id/2.html">李小璐</a></dd>
				</dl>
			</div>
		</div>
		<div class="wdu-part-layout wdu-back-whits">
			<div class="wdu-list-head wdu-part-rows wdu-padding">
				<h2 class="wdu-font-xvi"><a href="/index.php/vod/show/by/time/id/2.html" class="wdu-text-bold wdu-text-green">按时间</a><a href="/index.php/vod/show/by/hits/id/2.html">按人气</a><a href="/index.php/vod/show/by/score/id/2.html">按评分</a></h2>
				<ul class="wdu-part-tips wdu-padding">
					<li><span class="wdu-more"><span class="wdu-hide-xs">当前第&nbsp;<span id="wdu-now" class="wdu-text-green wdu-text-bold">1</span>&nbsp;页，</span>共&nbsp;<span id="wdu-count" class="wdu-text-green wdu-text-bold">0</span>&nbsp;个影片</span></li>
				</ul>
			</div>
			<ul class="wdu-list-info wdu-part-rows">
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/23082.html" data-original="https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2534174549.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">4.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至10</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/23082.html">悬浮聚会第一季</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">丽亚娜·莱伯拉托,哈莉·拉姆,阿琼娜·亚历克苏丝,布芮妮·邱</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/23062.html" data-original="https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2462599629.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">7.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至3</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/23062.html">创业时代</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">黄轩,杨颖,周一围,宋轶</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/22615.html" data-original="https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2535390387.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">1.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至22</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/22615.html">毛丫丫被婚记/最好的遇见</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">明道,颖儿,马天宇,恬妞</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/22592.html" data-original="https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2535740891.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">9.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至18</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/22592.html">右玉和她的县委书记们</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">黄品沅,缪婷如,那志东,印小天</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/22534.html" data-original="https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2393803311.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">8.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至28</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/22534.html">长江往事/喋血长江</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">王雨,王媛可,刘雨鑫,李建义</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/22511.html" data-original="http://wx1.sinaimg.cn/small/eaefd6efgy1fvqotw5045j207i0a0t9p.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">1.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至32</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/22511.html">棒棒的幸福生活</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">赵亮,袁志博,叮当,左佳</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/22471.html" data-original="https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2517388387.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">1.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至23</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/22471.html">你迟到的许多年</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">黄晓明,殷桃,秦海璐,曹炳琨</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/22430.html" data-original="https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2524165924.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">7.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至23</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/22430.html">颤抖吧阿部之朵星风云</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">郑业成,安悦溪,徐嘉苇,徐沐婵</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/22830.html" data-original="https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2457034854.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">9.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至20</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/22830.html">彭湃</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">吴其江,王媛可,张笑君,周舟</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/11590.html" data-original="https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2522104204.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">10.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至72</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/11590.html">娘道</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">岳丽娜,于毅,张少华,史可</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/10660.html" data-original="http://wx4.sinaimg.cn/mw690/eaefd6efgy1fthx0y5e7ej20go0b4402.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">3.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至13</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/10660.html">爱的3.14159</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">邵雨薇,吴思贤,陈大天,李婕,杨小黎,蓝雅芸,许时豪</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/15088.html" data-original="https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2528646061.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">1.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至13</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/15088.html">爱的3.14159</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">吴思贤,邵雨薇,陈大天,杨小黎</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/23118.html" data-original="http://img3.doubanio.com/view/photo/s_ratio_poster/public/p2536491976.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">3.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至10</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/23118.html">你是我的毒玫瑰</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">颂恩·宋帕山,瓦拉妮·塔瓦翁</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/23085.html" data-original="http://img3.doubanio.com/view/photo/s_ratio_poster/public/p2535742933.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">7.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至1</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/23085.html">大恋爱~与将我忘记的你</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">户田惠梨香,室毅</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/23084.html" data-original="http://img1.doubanio.com/view/photo/s_ratio_poster/public/p2533997208.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">9.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至2</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/23084.html">罗曼诺夫后裔</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">伊莎贝尔·于佩尔,艾伦·艾克哈特,克里斯蒂娜·亨德里克斯,戴安·琳恩</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/23081.html" data-original="http://img3.doubanio.com/view/photo/s_ratio_poster/public/p2536581881.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">10.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至1</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/23081.html">昭和元禄落语心中</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">冈田将生,龙星凉,成海璃子,大政绚</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/23080.html" data-original="http://img3.doubanio.com/view/photo/s_ratio_poster/public/p2535332500.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">7.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至1</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/23080.html">泰坦第一季</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">布伦顿·思韦茨,蒂根·克罗夫特,安娜·迪奥普,林赛·高特</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/23069.html" data-original="http://img1.doubanio.com/view/photo/s_ratio_poster/public/p2535660968.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">5.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至1</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/23069.html">十二夜</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">韩胜妍,申譞洙,张铉诚,艺秀晶</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/23067.html" data-original="http://img3.doubanio.com/view/photo/s_ratio_poster/public/p2196105151.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">1.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至1</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/23067.html">军情五处第十季</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">彼得·弗斯,劳拉·普沃,妮可拉·沃克,马克斯·布朗</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/23065.html" data-original="http://img3.doubanio.com/view/photo/s_ratio_poster/public/p2511920701.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">1.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至1</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/23065.html">忘却的幸子</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">高畑充希,吹越满,布施绘里,逢泽莉娜</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/23064.html" data-original="http://img3.doubanio.com/view/photo/s_ratio_poster/public/p2535296732.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">3.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至1</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/23064.html">我与尾巴与神乐坂</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">相叶雅纪,广末凉子,小泷望,趣里</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/23059.html" data-original="http://img3.doubanio.com/view/photo/s_ratio_poster/public/p2534588882.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">9.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至10</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/23059.html">鬼入侵</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">米契尔·哈思曼,卡拉·古奇诺,亨利·托马斯,伊莉莎白·里瑟</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/22809.html" data-original="http://img1.doubanio.com/view/photo/s_ratio_poster/public/p2329808599.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">1.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至5</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/22809.html">牵牛花与小龙虾</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">BigM,Krittarit,Butprohm,凯特·索尼娅·辛哈,Pai</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/22779.html" data-original="http://img3.doubanio.com/view/photo/s_ratio_poster/public/p2535979515.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">1.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至2</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/22779.html">僵尸国度第五季</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">美国欧美剧</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/22777.html" data-original="http://img1.doubanio.com/view/photo/s_ratio_poster/public/p2535295228.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">7.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至2</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/22777.html">黑色丑闻</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">山口纱弥加,安藤政信,松井玲奈,若叶龙也</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/22756.html" data-original="http://img3.doubanio.com/view/photo/s_ratio_poster/public/p2536023516.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">1.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至2</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/22756.html">威尔和格蕾丝第十季</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">艾瑞克·麦柯马克,黛博拉·梅辛,梅根·莫拉莉,西恩·海耶斯</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/22754.html" data-original="http://img3.doubanio.com/view/photo/s_ratio_poster/public/p2532518615.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">8.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至3</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/22754.html">新夏威夷神探</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">杰伊·埃尔南德斯,佩蒂塔·维克斯,扎迦利·奈顿,Stephen,Hill</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/22474.html" data-original="http://img3.doubanio.com/view/photo/s_ratio_poster/public/p2534125280.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">7.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至5</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/22474.html">第三种魅力</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">徐康俊,李絮,杨东根,李允芝</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/22472.html" data-original="http://img1.doubanio.com/view/photo/s_ratio_poster/public/p2535399828.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">8.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至3</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/22472.html">反恐特警组第二季</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">吉恩·法贝尔,赛·甘德沃尔,吉米·让-刘易斯,谢默·摩尔</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/22393.html" data-original="http://img1.doubanio.com/view/photo/s_ratio_poster/public/p2534877548.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">7.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至3</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/22393.html">海军罪案调查处第十六季</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">马克·哈蒙</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/22308.html" data-original="http://img1.doubanio.com/view/photo/s_ratio_poster/public/p2530618269.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">8.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至6</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/22308.html">时光的魔咒</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">杰西达邦·福尔迪,Mew</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/22260.html" data-original="http://img3.doubanio.com/view/photo/s_ratio_poster/public/p2516325481.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">8.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至3</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/22260.html">边境城镇第一季</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">Ville,Virtanen,Anu,Sinisalo,Matleena,Kuusniemi</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/15271.html" data-original="http://img1.doubanio.com/view/photo/s_ratio_poster/public/p2522562377.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">6.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至4</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/15271.html">糟心的我/糟心生活第一季</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">保罗·安德斯坦,艾斯林·贝亚,莎拉尤·拉奧,詹姆斯·巴克利</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/15224.html" data-original="http://img3.doubanio.com/view/photo/s_ratio_poster/public/p2507539252.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">1.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至5</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/15224.html">发现女巫第一季</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">马修·古迪,泰莉莎·帕尔墨,艾莎·哈特,欧文·蒂尔</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/15058.html" data-original="http://img3.doubanio.com/view/photo/s_ratio_poster/public/p2510180883.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">4.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至26</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/15058.html">在你背上扣球</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">朴英奎,严贤京,黄雨瑟惠,朴海美,</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/14974.html" data-original="http://img3.doubanio.com/view/photo/s_ratio_poster/public/p2533524456.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">3.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至6</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/14974.html">报社第一季/新闻之争</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">本·卓别林,夏洛特·莱利,大卫·苏切</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/14969.html" data-original="http://img3.doubanio.com/view/photo/s_ratio_poster/public/p2533845845.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">9.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至6</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/14969.html">大林</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">申东烨,郑尚勋,崔嬉序,柳善皓</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/10961.html" data-original="http://img1.doubanio.com/view/photo/s_ratio_poster/public/p2201468437.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">3.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至12</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/10961.html">凡尘星/星陨凡尘</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">Tasit,Sinkanawiwat,Jakjaan,Akumsiri,Suwannasuk</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/10732.html" data-original="http://img1.doubanio.com/view/photo/s_ratio_poster/public/p2528678897.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">4.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至51</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/10732.html">爱到最后</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">李英雅,姜恩卓,洪秀儿,沈智浩</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/10283.html" data-original="http://wx4.sinaimg.cn/small/eaefd6efgy1ft52jh9aw7j20bu0c5wf2.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">9.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至69</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/10283.html">女兵日记(台剧)2018</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">台湾台湾剧</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/9934.html" data-original="http://wx4.sinaimg.cn/small/eaefd6efgy1fsxhu6zn3wj209v09ymxb.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">1.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至74</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/9934.html">大时代(台湾)</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">陈美凤,江祖平,王瞳</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/5361.html" data-original="http://img3.doubanio.com/view/photo/s_ratio_poster/public/p2513475312.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">6.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至10</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/5361.html">公鸡小子</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">柏·梅娜妲,Tarn,Kanya,Jinn,Jinna,Navarat,Aoom,Angkana,Woraruttanachai</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/5226.html" data-original="http://img3.doubanio.com/view/photo/s_ratio_poster/public/p2521695393.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">4.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至106</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/5226.html">明日也晴朗</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">薛仁雅,,陳柱亨,荷承里,李昌旭</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/5139.html" data-original="http://img3.doubanio.com/view/photo/s_ratio_poster/public/p2509949972.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">7.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至197</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/5139.html">金家好媳妇</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">黄少祺,韩瑜,谢承均,曾莞婷</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/851.html" data-original="http://img3.doubanio.com/view/photo/s_ratio_poster/public/p2518397164.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">8.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至427</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/851.html">爱回家之开心速递粤语</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">刘丹,单立文,汤盈盈,吕慧仪</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/367.html" data-original="http://wx2.sinaimg.cn/small/eaefd6efgy1ftxftv118nj20nf0fc7mm.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">4.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至10</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/367.html">不期而爱</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">Perth,Tanapon,Sukumpantanasan</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/23060.html" data-original="https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2530796777.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">6.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至6</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/23060.html">降龙之白露为霜</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">杨昊铭,赵诚宇,李彦漫,唐本</span></li>
				<li class="wdu-list-item wdu-padding wdu-col-xs4 wdu-col-sm3 wdu-col-md2"><a class="wdu-list-pics wdu-lazy wdu-part-2by3" href="/index.php/vod/detail/id/22867.html" data-original="https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2535590271.jpg"><span class="wdu-list-play wdu-hide-xs"></span><span class="wdu-list-score wdu-font-xii wdu-back-green">4.0</span><span class="wdu-list-remarks wdu-font-xii wdu-text-white wdu-text-center">更新至5</span></a><a class="wdu-list-title wdu-font-xiv wdu-text-center wdu-text-sm-left wdu-visible wdu-part-eone" href="/index.php/vod/detail/id/22867.html">跳跃生命线国语</a><span class="wdu-list-desc wdu-font-xii wdu-visible wdu-part-eone wdu-text-muted wdu-hide-xs wdu-show-sm-block">马德钟,何广沛,刘佩玥,陈滢</span></li>
			</ul>
			<div class="wdu-page-info wdu-text-center">
				<a class="wdu-btns-info wdu-rims-info wdu-hide wdu-show-xs-inline wdu-btns-disad" href="/index.php/vod/show/id/2/page/1.html">首页</a><a class="wdu-btns-info wdu-rims-info wdu-btns-disad" href="/index.php/vod/show/id/2/page/1.html">上一页</a><a class="wdu-btns-info wdu-rims-info wdu-hide wdu-show-sm-inline wdu-btns-green" href="javascript:;">1</a><a class="wdu-btns-info wdu-rims-info wdu-hide wdu-show-sm-inline" href="/index.php/vod/show/id/2/page/2.html">2</a><a class="wdu-btns-info wdu-rims-info wdu-hide wdu-show-sm-inline" href="/index.php/vod/show/id/2/page/3.html">3</a><a class="wdu-btns-info wdu-rims-info wdu-hide wdu-show-sm-inline wdu-btns-disad" href="javascript:;">...</a><a class="wdu-btns-info wdu-rims-info wdu-hide wdu-show-sm-inline" href="/index.php/vod/show/id/2/page/36.html">36</a><a class="wdu-btns-info wdu-rims-info wdu-hide wdu-show-xs-inline" href="javascript:;">1/36</a><a class="wdu-btns-info wdu-rims-info" href="/index.php/vod/show/id/2/page/2.html">下一页</a><a class="wdu-btns-info wdu-rims-info wdu-hide wdu-show-xs-inline" href="/index.php/vod/show/id/2/page/36.html">尾页</a>
			</div>
			<script type="text/javascript">if(document.getElementById('wdu-now')) document.getElementById('wdu-now').innerHTML='1';if(document.getElementById('wdu-count')) document.getElementById('wdu-count').innerHTML='1706';</script>
		</div>
	</div>
</div>
<?php
require('footer.php');
?>